name: Manual workflow

on:
  workflow_dispatch:
    inputs:
      newVersion:
        description: 'New Version'
        default: '1.0.2'
        required: true

jobs:

  updateBinaryTarget:
    runs-on: macos-latest
    permissions:
      # Give the default GITHUB_TOKEN write permission to commit and push the
      # added or changed files to the repository.
      contents: write

    steps:
    - uses: actions/checkout@v3
    - name: Update Package.swift
      run: |
        ./scripts/updateChecksum.sh ${{ github.event.inputs.newVersion }}
    - name: Commit Changes
      uses: stefanzweifel/git-auto-commit-action@v4
      with:
        tagging_message: 'v${{ github.event.inputs.newVersion }}'
    - name: Create Release
      id: create_release 
      uses: actions/create-release@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} # This token is provided by Actions, you do not need to create your own token
      with:
        tag_name: ${{ github.ref }}
        release_name: Release ${{ github.ref }}

    # - name: Create Pull Request
    # uses: peter-evans/create-pull-request@v5
      # with:
      #   token: ${{ secrets.GITHUB_TOKEN }}
      #   author: ${{ github.actor }} <${{ github.actor }}@users.noreply.github.com>