name: Manual workflow

on:
  workflow_dispatch:
    inputs:
      newVersion:
        description: 'New Version'
        default: '1.0.2'
        required: true

jobs:

  updateBinaryTarget:
    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v3
    - name: Update Package.swift
      run: |
        ./scripts/updateChecksum.sh ${{ github.event.inputs.newVersion }}
    - name: Create Pull Request
      uses: peter-evans/create-pull-request@v3
      with:
        token: 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
        