name: Manual workflow

on:
  workflow_dispatch:
    inputs:
      newVersion:
        description: 'New Version'
        default: '1.0.2'
        required: true

jobs:

  updateBinaryTarget:
    runs-on: macos-latest
    permissions:
      # Give the default GITHUB_TOKEN write permission to commit and push the
      # added or changed files to the repository.
      contents: write

    steps:
    - uses: actions/checkout@v3
    - name: Update Package.swift
      run: |
        ./scripts/updateChecksum.sh ${{ github.event.inputs.newVersion }}
    - name: Create Pull Request
      uses: peter-evans/create-pull-request@v5
      with:
        token: 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
        author: ${{ github.actor }} <${{ github.actor }}@users.noreply.github.com>